steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'packages/services/message-orchestrator/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/message-orchestrator:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/message-orchestrator:latest'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/message-orchestrator:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/message-orchestrator:latest'
timeout: 1200s
options:
  machineType: 'N1_HIGHCPU_8'
